---
title: "Tarea4_Resuelta"
author: "Pedro Gutiérrez"
date: "2025-05-16"
output: html_document
---
<style>
body {
text-align: justify}
</style>

```{python}
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
from statsmodels.tsa.seasonal import seasonal_decompose 
import matplotlib.colors as mcolors
import seaborn as sns 
from statsmodels.tsa.stattools import acf 
from statsmodels.tsa.stattools import adfuller
import calendar
import plotly.graph_objects as go
from statsmodels.tsa.ar_model import AutoReg
```


# Gráficas de una serie temporal {.tabset}

Las **series temporales** es una sucesión de observaciones registradas a intervalos de tiempo regulares. Son fundamentales en modelado predictivo y análisis de datos en diversas disciplinas.


Consideraremos el tipo de cambio nominal (pesos por dólar) con una frecuencia mensual.

## Serie 

```{python}
inegi_data = pd.read_excel("Análisis númerico/Complementos/inegi_data.xlsx", parse_dates=['Periodo'])
inegi_data['Periodo'] = pd.to_datetime(inegi_data["Periodo"])
filtered_data = inegi_data[inegi_data['Periodo'].dt.year >= 2016]

print(filtered_data["Periodo"].dt.year.unique())
```

```{python}
inegi_xts = pd.Series(filtered_data["TIIE"].values, index=filtered_data['Periodo']).dropna()
print(inegi_xts.describe())

plt.figure(figsize=(8, 6))
plt.plot(inegi_xts, label="TIIE", color=sns.color_palette("magma", n_colors=5)[3])
plt.title("Serie Temporal de las TIIE")
plt.xlabel("Periodo")
plt.ylabel("TIIE")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()

```


## Comparación anual
```{python}
plt.style.use('seaborn-v0_8-whitegrid')  
sns.set_palette("viridis")  

inegi_xts_df = inegi_xts.to_frame(name="TIIE")
inegi_xts_df["Año"] = inegi_xts.index.year
inegi_xts_df["Mes"] = inegi_xts.index.month

plt.figure(figsize=(8, 6))
ax = sns.lineplot(
    data=inegi_xts_df, 
    x="Mes", 
    y="TIIE", 
    hue="Año",
    linewidth=2.5,
    marker="o", 
    markersize=8
)

plt.title("Comparación Anual de la TIIE", fontsize=14, pad=20, fontweight='bold')
plt.xlabel("Mes", fontsize=12)
plt.ylabel("Tasa TIIE (%)", fontsize=14)
plt.xticks(range(1, 13))  
plt.grid(True, linestyle=':', alpha=0.7)  

plt.legend(
    title='Año',
    title_fontsize='13',
    fontsize='11',
    frameon=True,
    shadow=True,
    bbox_to_anchor=(1.05, 1),
    loc='upper left'
)

plt.tight_layout()  
sns.despine()  
plt.show()
```


## Comparación mensual

```{python}
df = filtered_data.copy()
df["Año"] = df["Periodo"].dt.year
df["Mes"] = df["Periodo"].dt.month

plt.figure(figsize=(8,6))
sns.lineplot(data=df, x="Año", y="TIIE", hue="Mes", marker="o", palette = sns.color_palette("magma", n_colors=12))

plt.xlabel("Año")
plt.ylabel("TIIE")
plt.title("TIIE Mensual")

mes = sorted(df["Mes"].unique())
labels = [calendar.month_abbr [m] for m in mes]
plt.legend(title="Mes", labels=labels)
plt.grid(True)
plt.tight_layout()
plt.show()
```

## Boxplot trimestral
```{python}
inegi_data["Periodo"] = pd.to_datetime(inegi_data["Periodo"])
inegi_data["Año"] = inegi_data["Periodo"].dt.year
inegi_data["Trimestre"] = inegi_data["Periodo"].dt.to_period("Q").astype(str)

filtered_data = inegi_data[(inegi_data["Año"] >= 2016) & (inegi_data["Año"] <= 2025)]

plt.figure(figsize=(8, 5))
sns.boxplot(
    data=filtered_data,
    x="Trimestre",
    y="TIIE",
    hue="Año",
    palette="dark"
)

plt.xlabel("Trimestre")
plt.ylabel("TIIE")
plt.title("Boxplot Trimestral de las TIIE (2016-2025)")
plt.legend(title="Año", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()
```

## Heatmap

```{python}
heatmap_data = inegi_xts_df.pivot_table(index='Mes', columns='Año', values='TIIE')
plt.figure(figsize=(8, 6))
sns.heatmap(heatmap_data, annot=True, fmt=".1f", cmap="YlGnBu", 
            linewidths=.5, cbar_kws={'label': 'Tasa TIIE (%)'})
plt.title("Evolución Anual de la TIIE (Heatmap)", fontsize=14, pad=20)
plt.xlabel("Año", fontsize=12)
plt.ylabel("Mes", fontsize=12)
plt.tight_layout()
plt.show()
```

## Surface

```{python}
df["Año"] = df["Periodo"].dt.year
df["Mes"] = df["Periodo"].dt.month

heatmap_df = df.pivot_table(values="TIIE", index="Mes", columns="Año", aggfunc="mean")
heatmap_df = heatmap_df.fillna(0)

Z = heatmap_df.values  
x = heatmap_df.columns.astype(str)  
y = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"]

fig = go.Figure(data=[go.Surface(z=Z, x=x, y=y, colorscale="greens")])
fig.update_layout(
    title='3D TIIE',
    scene=dict(
        xaxis_title="Año",
        yaxis_title="Mes",
        zaxis_title="TIIE"
    ),
    autosize=True,
    height=800
)

fig.show()
```

# Estadísticas de una serie temporal

## Media muestral

La media muestral es el promedio de los valores de la serie temporal a lo largo del tiempo. Se calcula como:

\begin{equation}
\bar{y}=\frac{1}{T} \sum_{t=1}^T y_t
\end{equation}

Donde $T$ es el número total de observaciones de la serie y $y_t$ es el valor de la serie en el tiempo $t$.

```{python}
mean = inegi_xts.mean()
print(mean)
```

## Varianza muestral 

La varianza muestral cuantifica la dispersión de los valores de la serie alrededor de su media. Se calcula como:


\begin{equation}
s^2=\frac{1}{T-1} \sum_{t=1}^T (y_t-\bar{y})^2
\end{equation}

```{python}
var =  inegi_xts.var()
print(var)
```

## Autocovarianza muestral

Cuantifica la covarianza entre dos valores de la serie separados por un retraso (lag) $k$. Se calcula como:

\begin{equation}
\gamma_k=\frac{1}{T} \sum_{t=k+1}^T (y_t-\bar{y})(y_{t-k}-\bar{y})
\end{equation}

En este caso $y_{t-k}$ es el valor de la serie en el tiempo $t-k$.


## Autocorrelación muestral {.tabset}

Es una versión normalizada de la autocovarianza, que mide la correlacion entre dos valores de la serie separados por un retraso $k$, se calcula como:

\begin{equation}
\rho_k=\frac{\gamma_k}{\gamma_0}
\end{equation}


### Autocorrelación

```{python}
autocorrelacion = acf(inegi_xts, fft="True", nlags=20)

plt.figure(figsize=(8,6))
plt.stem(range(len(autocorrelacion)), autocorrelacion, basefmt=" ")
plt.title("Autocorrelación")
plt.xlabel("Lag")
plt.ylabel("Autocorrelación")
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()
```


```{python}
acf_values = acf(inegi_xts, fft=True, nlags=20)

plt.figure(figsize=(8,6))
markerline, stemlines, baseline = plt.stem(range(len(acf_values)), acf_values, basefmt=" ")
plt.setp(stemlines, 'linewidth', 1) 
plt.setp(markerline, 'markersize', 5) 
conf_int = 1.96 / np.sqrt(len(inegi_xts))
plt.axhspan(-conf_int, conf_int, alpha=0.1, color='blue', label='Confidence Interval')

plt.title("Autocorrelation Function (ACF)")
plt.xlabel("Lag")
plt.ylabel("Autocorrelation")
plt.grid(True, linestyle="--", alpha=0.4)
plt.legend()
plt.show()
```

### Lags

```{python}
max_lag= 14
plt.figure(figsize=(4,2))

for lag in range (1, max_lag + 1): 
  plt.plot(inegi_xts.index, inegi_xts.shift(lag), label=f"lag{lag}")

plt.title('Lags')
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()
```

## Estacionariedad

Una serie temporal es **estacionaria** si la media y la varianza es constante a lo largo del tiempo y la autocovarianza entre dos puntos depende sólo de la distancia temporal entre ellos, no del momento específico.

Se aplica la prueba de Dickey-Fuller (ADF)



Como el p-value > 0.05, no existe suficiente evidencia estadística en contra de la hipótesis nula (la serie no  es estacionaria).

```{python}
estacionariedad = adfuller(inegi_xts)
print("estacionariedad")
```

## Diferenciación

Si la serie no es estacionaria se puede aplicar diferenciación para eliminar la tendencia.

```{python}
inegi_xts = pd.Series(filtered_data["TIIE"].values, index=filtered_data["Periodo"]).dropna()
inegi_diff = inegi_xts.diff().dropna()

plt.figure(figsize=(8,6))
plt.plot(inegi_diff, label="Diferenciación de la Serie", color= "darkgreen")
plt.title("Serie Temporal Diferenciada")
plt.xlabel("Periodo")
plt.ylabel("Diferenciación")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()
```


# Descomposición  {.tabset}

Una serie temporal $y_t$ puede descomponerse en la suma (aditiva) de sus componentes principales:


\begin{equation}
y_t = T_t+S_t+R_t
\end{equation}

Donde $T_t$ es la tendencia (movimiento a largo plazo), $S_t$ es la estacionalidad (patrones repetitivos en intervalos regulares) y $R_t$ es el residuo (ruido aleatorio). O bien, de manera multiplicativa:

\begin{equation}
y_t = T_t S_t R_t
\end{equation}

## Serie original

```{python}
descomposicion = seasonal_decompose(inegi_xts, model= "additive", period=12)

plt.figure(figsize=(8,6))
descomposicion.plot()
plt.show()
```

## Serie diferenciada

```{python}
inegi_diff = inegi_xts.diff().dropna()
descomposicion_diff = seasonal_decompose(inegi_diff, model= "additive", period=12)

plt.figure(figsize=(8,6))
descomposicion_diff.plot()
plt.show()
```


# AutoRegresión {.tabset}

## Coeficientes
```{python}
inegi_ts = inegi_xts.asfreq("MS") 
inegi_ar_model = AutoReg(inegi_ts, lags=5, old_names=False).fit()
print(inegi_ar_model.summary())
```

## Gráfica
```{python}
inegi_ts.index = pd.to_datetime(inegi_ts.index, errors="coerce") 
inegi_ar_res = pd.DataFrame({
  "inegi": inegi_ts, 
  "inegi_fitted": inegi_ts - inegi_ar_model.resid
})

plt.figure(figsize=(10,6))
plt.plot(inegi_ar_res.index, inegi_ar_res["inegi"], label="Original", color="darkgreen", alpha=0.4)
plt.plot(inegi_ar_res.index, inegi_ar_res["inegi_fitted"], label="Ajustado",
color="pink",linestyle="--")

plt.title("Datos Originales y Ajustados del Modelo Autoregresivo")
plt.xlabel("Periodo")
plt.ylabel("Valores")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()
```

## Residuos

```{python}
residuos = inegi_ar_model.resid  # Usamos .resid para obtener los residuos

plt.figure(figsize=(10, 6))
plt.plot(residuos.index, residuos, label='Residuos', color='darkgreen', linewidth=1)
plt.axhline(y=0, color='red', linestyle='--', alpha=0.5)  # Línea de referencia en cero
plt.title('Análisis de Residuos del Modelo AR', fontsize=14, pad=15)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Residuos', fontsize=12)
plt.legend(loc='upper right', fontsize=10)
plt.grid(True, linestyle=':', alpha=0.7)
plt.tight_layout()
plt.show()

# Opcional: Gráfico Q-Q para normalidad de residuos
import scipy.stats as stats
plt.figure(figsize=(8, 6))
stats.probplot(residuos, dist="norm", plot=plt)
plt.title('Gráfico Q-Q de Residuos', fontsize=14)
plt.tight_layout()
plt.show()
```

## Forecast
```{python}
forecast_steps = 12
forecast_valores = inegi_ar_model.forecast(steps=forecast_steps)
forecast_index = pd.date_range(start=inegi_ts.index[-1] + pd.offsets.MonthBegin(1), periods=forecast_steps, freq="MS")

inegi_forecast = pd.DataFrame({
  "Forecast": forecast_valores
},index=forecast_index)

plt.figure(figsize=(10,6))
plt.plot(inegi_ts, label="Original", color="blue")
plt.plot(inegi_ar_res["inegi_fitted"], label="Ajustado", color="darkgreen")
plt.plot(inegi_forecast.index, inegi_forecast["Forecast"], label="Pronóstico", color="green", linestyle="--")
plt.title=("Forecast del Modelo Autoregresivo")
plt.xlabel("Periodo")
plt.ylabel("Valores")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()
```

 
